name: Build and Test
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS to build on. Ubuntu is faster, MacOS supports iOS builds, Windows is unsupported
        options:
          - macos-latest
          - ubuntu-latest
      platform:
        type: choice
        description: Platform to build for
        options:
          - android
          - ios
      profile:
        type: choice
        description: Build profile to use
        options:
          - development
          - preview
          - production
jobs:
  build:
    # strategy:
    #   matrix:
    #     include:
    #       - platform: "ios"
    #         os: "macos-latest"
    #       - platform: "android"
    #         os: "ubuntu-latest"

    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy Google Services files from secrets
        run: echo ${{ secrets.GOOGLE_SERVICES_ANDROID_BASE64 }} | base64 --decode > ./google-services.json && echo ${{ secrets.GOOGLE_SERVICES_IOS_BASE64 }} | base64 --decode > ./GoogleService-Info.plist

      - name: Yarn install
        uses: ./.github/actions/yarn-install

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup EAS local builds
        run: yarn global add eas-cli-local-build-plugin

      # - name: Test
      #   run: yarn test

      - name: Build
        run: |
          eas build --local \
            --non-interactive \
            --output=./out \
            --platform=${{ github.event.inputs.platform }} \
            --profile=${{ github.event.inputs.profile }}
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ping-4-gitlab-${{ github.event.inputs.platform }}
          path: out
