name: Commitlint
on:
  pull_request:
    branches:
      - master

jobs:
  run-commitlint-on-pr:
    name: "Lint Commits"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Yarn install
        uses: ./.github/actions/yarn-install

      - name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
