name: Build and deploy

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy Google Services files from secrets
        run: echo ${{ secrets.GOOGLE_SERVICES_ANDROID_BASE64 }} | base64 --decode > ./google-services.json && echo ${{ secrets.GOOGLE_SERVICES_IOS_BASE64 }} | base64 --decode > ./GoogleService-Info.plist

      - name: Yarn install
        uses: ./.github/actions/yarn-install

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        run: npx eas-cli build --platform all --non-interactive

      - name: Get version from manifest
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "app.json"
          prop_path: "expo.version"

      - name: Bump build and tag on master
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "chore: bumped build numbers"
          commit_options: "--no-verify"
          tagging_message: "v${{steps.version.outputs.prop}}"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Check for EXPO_APPLE_APP_SPECIFIC_PASSWORD
        run: |
          if [ -z "${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}" ]; then
            echo "You must provide an EXPO_APPLE_APP_SPECIFIC_PASSWORD to deploy to testflight"
          fi

      - name: Check for EXPO_APPLE_ID
        run: |
          if [ -z "${{ secrets.EXPO_APPLE_ID }}" ]; then
            echo "You must provide an EXPO_APPLE_ID to deploy to testflight"
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Yarn install
        uses: ./.github/actions/yarn-install

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Submit to testflight
        run: EXPO_APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }} EXPO_APPLE_ID=${{ secrets.EXPO_APPLE_ID }} npx eas-cli submit -p ios --latest --non-interactive

      - name: Submit to playstore
        run: npx eas-cli submit -p android --latest --non-interactive
